### ISSUE TITLE
Suggestion: Mac OS system detection on u_system function.

### ISSUE THREAD

**Issue by diegoviador** [andresclua/js-util#9]
It would be nice to have a mac os option for cases like [this one.](https://github.com/terra-hq/bws-wp-theme/blob/70d0862112f8cd4eae85ebae8279f0f7a319e514/src/js/modules/DetectOS.js#L5)

![image](https://github.com/andresclua/js-util/assets/160519480/6c528798-4e72-4736-88fb-b2d35acef2fb)

**Comment by andresclua** [comment]
Hey @diegoviador , can you elaborate more?
My intention was always to perform like this.


```
var isIOs =  u_system('ios')); returns true or false.
if(isIOS){
 // execture something if ios devices
}else{
// execute something for windows devices
}
```

**Comment by diegoviador** [comment]
In [the example above](https://github.com/terra-hq/bws-wp-theme/blob/70d0862112f8cd4eae85ebae8279f0f7a319e514/src/js/modules/DetectOS.js#L5), there's a method called `handleOperativeSystem()` which utilizes mac os distinction. Maybe It's not needed in projects that use JsUtils, but I found odd that you could use mac os in isDevice but not with u_system.

**Comment by andresclua** [comment]
hey @diegoviador! got your point.

```
u_system('mac')
```

 Introduce this new option.
 pls update library, let me know if that is ok, and if so, close this issue.

**Comment by diegoviador** [comment]
Perfect @andresclua! Works wonderfully. I'll make sure to use it in future updates as well.
